services:
  - type: web
    runtime: docker
    name: handwritten-ocr-backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: CUDA_VISIBLE_DEVICES
        value: ""